FROM python:3.10-slim

WORKDIR /app

COPY shared /app/shared

COPY gatewayApi /app

COPY gatewayApi/requirements.txt /app/requirements.txt

RUN pip install --no-cache-dir --upgrade pip
RUN pip install --no-cache-dir -r /app/requirements.txt

RUN mkdir -p /app/logs && chmod -R 777 /app/logs

EXPOSE 8000

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]