version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    logging:
      driver: "json-file"
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "${APP_PORT}", "--reload", "--log-level", "debug"]
