version: "3.9"
services:
  product_db:
    image: postgres
    container_name: product_service_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_PRODUCT}
    ports:
      - "${POSTGRES_PORT_PRODUCT}:5432"
    volumes:
      - product_postgres_data:/var/lib/postgresql/data
  product_app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: product_service_app
    depends_on:
      - product_db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_PRODUCT}
      POSTGRES_HOST: ${POSTGRES_HOST_PRODUCT}
      POSTGRES_PORT: ${POSTGRES_PORT_PRODUCT}
      APP_PORT: ${APP_PORT_PRODUCT}
    ports:
      - "${APP_PORT_PRODUCT}:8000"
    volumes:
      - .:/app
      - ./app/logs:/app/logs
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

volumes:
  product_postgres_data: