version: "3.9"
services:
  db:
    image: postgres
    container_name: user_service_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_USER}
    ports:
      - "${POSTGRES_PORT_USER}:5432"
    volumes:
      - user_postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: user_service_app
    depends_on:
      - db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_USER}
      POSTGRES_HOST: ${POSTGRES_HOST_USER}
      POSTGRES_PORT: ${POSTGRES_PORT_USER}
      APP_PORT: ${APP_PORT_USER}
    ports:
      - "${APP_PORT_USER}:8000"
    volumes:
      - .:/app
      - ./logs:/app/logs
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "${APP_PORT_USER}", "--reload"]
volumes:
  user_postgres_data: