version: "3.9"
services:
  db:
    image: postgres
    container_name: user_service_db
    restart: always
    environment:
      POSTGRES_USER: ${USER_POSTGRES_USER}
      POSTGRES_PASSWORD: ${USER_POSTGRES_PASSWORD}
      POSTGRES_DB: ${USER_POSTGRES_DB}
    ports:
      - "${USER_POSTGRES_PORT}:5432"
    volumes:
      - user_postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: user_service_app
    depends_on:
      - db
    environment:
      - PYTHONPATH=/app
      - POSTGRES_USER=${USER_POSTGRES_USER}
      - POSTGRES_PASSWORD=${USER_POSTGRES_PASSWORD}
      - POSTGRES_DB=${USER_POSTGRES_DB}
      - POSTGRES_HOST=${USER_POSTGRES_HOST}
      - POSTGRES_PORT=${USER_POSTGRES_PORT}
      - APP_PORT=${USER_APP_PORT}
    ports:
      - "${USER_APP_PORT}:${USER_APP_PORT}"
    volumes:
      - .:/app
      - ./logs:/app/logs
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "${USER_APP_PORT}", "--reload"]

volumes:
  user_postgres_data: