version: "3.9"
services:
  company_db:
    image: postgres
    container_name: company_service_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER_COMPANY}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_COMPANY}
      POSTGRES_DB: ${POSTGRES_DB_COMPANY}
    ports:
      - "${POSTGRES_PORT_COMPANY}:5432"
    volumes:
      - company_postgres_data:/var/lib/postgresql/data
  company_app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: company_service_app
    depends_on:
      - company_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER_COMPANY}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_COMPANY}
      POSTGRES_DB: ${POSTGRES_DB_COMPANY}
      POSTGRES_HOST: ${POSTGRES_HOST_COMPANY}
      POSTGRES_PORT: ${POSTGRES_PORT_COMPANY}
      APP_PORT: ${APP_PORT_COMPANY}
    ports:
      - "${APP_PORT_COMPANY}:8000"
    volumes:
      - .:/app
      - ./app/logs:/app/logs
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  company_postgres_data: